	<div class="modal fade" id="killercage7" tabindex="-1" role="dialog" aria-labelledby="killercage7Label" aria-hidden="true">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title">
						Killer Cage Size 7
					</h5>
				</div>
				<div class="modal-body">
					<table class="table table-sm table-striped">
						<thead>
							<tr>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
								<td>Digits</td>
								<td>Total</td>
							</tr>
						</thead>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>1234567</td>
							<td>28</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>1234568</td>
							<td>29</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>1234578</td>
							<td>1234569</td>
							<td>30</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>1234678</td>
							<td>1234579</td>
							<td>31</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td>1235678</td>
							<td>1234679</td>
							<td>1234589</td>
							<td>32</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td>1245678</td>
							<td>1235679</td>
							<td>1234689</td>
							<td>33</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td>1345678</td>
							<td>1245679</td>
							<td>1235689</td>
							<td>1234789</td>
							<td>34</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td>2345678</td>
							<td>1345679</td>
							<td>1245689</td>
							<td>1235789</td>
							<td>35</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td>2345679</td>
							<td>1345689</td>
							<td>1245789</td>
							<td>1236789</td>
							<td>36</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td>2345689</td>
							<td>1345789</td>
							<td>1246789</td>
							<td>37</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td>2345789</td>
							<td>1346789</td>
							<td>1256789</td>
							<td>38</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>2346789</td>
							<td>1356789</td>
							<td>39</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>2356789</td>
							<td>1456789</td>
							<td>40</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>2456789</td>
							<td>41</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>3456789</td>
							<td>42</td>
						</tr>
					</table>
				</div>
				<div class="modal-footer">
				</div>
			</div>
		</div>
	</div>