	<div class="modal fade" id="killercage3" tabindex="-1" role="dialog" aria-labelledby="killercage3Label" aria-hidden="true">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title">
						Killer Cage Size 3
					</h5>
				</div>
				<div class="modal-body">
					<table class="table table-sm table-striped" style="font-size:60%;">
						<thead>
							<tr>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
								<td>Digits</td>
								<td>Total</td>
							</tr>
						</thead>
						<tbody>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>123</td>
							<td>6</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>124</td>
							<td>7</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>134</td>
							<td>125</td>
							<td>8</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>234</td>
							<td>135</td>
							<td>126</td>
							<td>9</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>235</td>
							<td>145</td>
							<td>136</td>
							<td>127</td>
							<td>10</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td>245</td>
							<td>236</td>
							<td>146</td>
							<td>137</td>
							<td>128</td>
							<td>11</td>
						</tr>
						<tr>
							<td></td>
							<td>345</td>
							<td>246</td>
							<td>237</td>
							<td>156</td>
							<td>147</td>
							<td>138</td>
							<td>129</td>
							<td>12</td>
						</tr>
						<tr>
							<td></td>
							<td>346</td>
							<td>256</td>
							<td>247</td>
							<td>238</td>
							<td>157</td>
							<td>148</td>
							<td>139</td>
							<td>13</td>
						</tr>
						<tr>
							<td>356</td>
							<td>347</td>
							<td>257</td>
							<td>248</td>
							<td>239</td>
							<td>167</td>
							<td>158</td>
							<td>149</td>
							<td>14</td>
						</tr>
						<tr>
							<td>456</td>
							<td>357</td>
							<td>348</td>
							<td>267</td>
							<td>258</td>
							<td>249</td>
							<td>168</td>
							<td>159</td>
							<td>15</td>
						</tr>
						<tr>
							<td>457</td>
							<td>367</td>
							<td>358</td>
							<td>349</td>
							<td>268</td>
							<td>259</td>
							<td>178</td>
							<td>169</td>
							<td>16</td>
						</tr>
						<tr>
							<td></td>
							<td>467</td>
							<td>458</td>
							<td>368</td>
							<td>359</td>
							<td>278</td>
							<td>269</td>
							<td>179</td>
							<td>17</td>
						</tr>
						<tr>
							<td></td>
							<td>567</td>
							<td>468</td>
							<td>459</td>
							<td>378</td>
							<td>369</td>
							<td>279</td>
							<td>189</td>
							<td>18</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td>568</td>
							<td>478</td>
							<td>469</td>
							<td>379</td>
							<td>289</td>
							<td>19</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>578</td>
							<td>569</td>
							<td>479</td>
							<td>389</td>
							<td>20</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>678</td>
							<td>579</td>
							<td>489</td>
							<td>21</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>679</td>
							<td>589</td>
							<td>22</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>689</td>
							<td>23</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>789</td>
							<td>24</td>
						</tr>
						</tbody>
					</table>
				</div>
				<div class="modal-footer">
				</div>
			</div>
		</div>
	</div>