	<div class="modal fade" id="killercage4" tabindex="-1" role="dialog" aria-labelledby="killercage4Label" aria-hidden="true">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title">
						Killer Cage Size 4
					</h5>
				</div>
				<div class="modal-body">
					<table class="table table-sm table-striped" style="font-size:57%;">
						<thead>
							<tr>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
								<td>Digits</td>
								<td>Total</td>
							</tr>
						</thead>
						<tbody>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>1234</td>
							<td>10</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>1235</td>
							<td>11</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>1245</td>
							<td>1236</td>
							<td>12</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>1345</td>
							<td>1246</td>
							<td>1237</td>
							<td>13</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>2345</td>
							<td>1346</td>
							<td>1256</td>
							<td>1247</td>
							<td>1238</td>
							<td>14</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>2346</td>
							<td>1356</td>
							<td>1347</td>
							<td>1257</td>
							<td>1248</td>
							<td>1239</td>
							<td>15</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>2356</td>
							<td>2347</td>
							<td>1456</td>
							<td>1357</td>
							<td>1348</td>
							<td>1267</td>
							<td>1258</td>
							<td>1249</td>
							<td>16</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td>2456</td>
							<td>2357</td>
							<td>2348</td>
							<td>1457</td>
							<td>1367</td>
							<td>1358</td>
							<td>1349</td>
							<td>1268</td>
							<td>1259</td>
							<td>17</td>
						</tr>
						<tr>
							<td></td>
							<td>3456</td>
							<td>2457</td>
							<td>2367</td>
							<td>2358</td>
							<td>2349</td>
							<td>1467</td>
							<td>1458</td>
							<td>1368</td>
							<td>1359</td>
							<td>1278</td>
							<td>1269</td>
							<td>18</td>
						</tr>
						<tr>
							<td></td>
							<td>3457</td>
							<td>2467</td>
							<td>2458</td>
							<td>2368</td>
							<td>2359</td>
							<td>1567</td>
							<td>1468</td>
							<td>1459</td>
							<td>1378</td>
							<td>1369</td>
							<td>1279</td>
							<td>19</td>
						</tr>
						<tr>
							<td>3467</td>
							<td>3458</td>
							<td>2567</td>
							<td>2468</td>
							<td>2459</td>
							<td>2378</td>
							<td>2369</td>
							<td>1568</td>
							<td>1478</td>
							<td>1469</td>
							<td>1379</td>
							<td>1289</td>
							<td>20</td>
						</tr>
						<tr>
							<td></td>
							<td>3567</td>
							<td>3468</td>
							<td>3459</td>
							<td>2568</td>
							<td>2478</td>
							<td>2469</td>
							<td>2379</td>
							<td>1578</td>
							<td>1569</td>
							<td>1479</td>
							<td>1389</td>
							<td>21</td>
						</tr>
						<tr>
							<td></td>
							<td>4567</td>
							<td>3568</td>
							<td>3478</td>
							<td>3469</td>
							<td>2578</td>
							<td>2569</td>
							<td>2479</td>
							<td>2389</td>
							<td>1678</td>
							<td>1579</td>
							<td>1489</td>
							<td>22</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td>4568</td>
							<td>3578</td>
							<td>3569</td>
							<td>3479</td>
							<td>2678</td>
							<td>2579</td>
							<td>2489</td>
							<td>1679</td>
							<td>1589</td>
							<td>23</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>4578</td>
							<td>4569</td>
							<td>3678</td>
							<td>3579</td>
							<td>3489</td>
							<td>2679</td>
							<td>2589</td>
							<td>1689</td>
							<td>24</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>4678</td>
							<td>4579</td>
							<td>3679</td>
							<td>3589</td>
							<td>2689</td>
							<td>1789</td>
							<td>25</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>5678</td>
							<td>4679</td>
							<td>4589</td>
							<td>3689</td>
							<td>2789</td>
							<td>26</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>5679</td>
							<td>4689</td>
							<td>3789</td>
							<td>27</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>5689</td>
							<td>4789</td>
							<td>28</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>5789</td>
							<td>29</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td>6789</td>
							<td>30</td>
						</tr>
						</tbody>
					</table>
				</div>
				<div class="modal-footer">
				</div>
			</div>
		</div>
	</div>