	<div class="modal fade" id="modal-puzzle-name" tabindex="-1" role="dialog" aria-labelledby="modal-puzzle-name" aria-hidden="true">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title">
						puzzle name
					</h5>
				</div>
				<div class="modal-body">
					<table class="table table-sm table-striped">
						<thead>
							<tr>
								<td></td>
								<td></td>
								<td></td>
								<td>Digits</td>
								<td>Total</td>
							</tr>
						</thead>
						<tbody>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td>12</td>
							<td>3</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td>13</td>
							<td>4</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td>23</td>
							<td>14</td>
							<td>5</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td>24</td>
							<td>15</td>
							<td>6</td>
						</tr>
						<tr>
							<td></td>
							<td>34</td>
							<td>25</td>
							<td>16</td>
							<td>7</td>
						</tr>
						<tr>
							<td></td>
							<td>35</td>
							<td>26</td>
							<td>17</td>
							<td>8</td>
						</tr>
						<tr>
							<td>45</td>
							<td>36</td>
							<td>27</td>
							<td>18</td>
							<td>9</td>
						</tr>
						<tr>
							<td>46</td>
							<td>37</td>
							<td>28</td>
							<td>19</td>
							<td>10</td>
						</tr>
						<tr>
							<td>56</td>
							<td>47</td>
							<td>38</td>
							<td>29</td>
							<td>11</td>
						</tr>
						<tr>
							<td></td>
							<td>57</td>
							<td>48</td>
							<td>39</td>
							<td>12</td>
						</tr>
						<tr>
							<td></td>
							<td>67</td>
							<td>58</td>
							<td>49</td>
							<td>13</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td>68</td>
							<td>59</td>
							<td>14</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td>69</td>
							<td>78</td>
							<td>15</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td>79</td>
							<td>16</td>
						</tr>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td>89</td>
							<td>17</td>
						</tr>
						</tbody>
					</table>
				</div>
				<div class="modal-footer">
				</div>
			</div>
		</div>
	</div>